#General
work dir: 40tp_exp
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim

sample sizes: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
