#General
work dir: 1tp_exp
slimfile: /pine/scr/l/s/lswhiteh/timesweeper-experiments/simple_sims/tps_vary/1_tp/sample-end-onePop-selectiveSweep-vcf.slim

sample sizes: [200]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
