#General
work dir: 10tp_exp
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim

sample sizes: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
ploidy: 2

#Simulation
reps: 2500
slim path: /proj/dschridelab/lswhiteh/timesweeper/src/SLiM/build/slim
