#General
work dir: missingness_0.2
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2

#Simulation
reps: 2500
slim path: /proj/dschridelab/lswhiteh/timesweeper/src/SLiM/build/slim
