#General
work dir: sample_size_5
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim
slim path: slim

sample sizes: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
ploidy: 2

#Simulation
reps: 2500
