#General
work dir: sample_size_5
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim

sample sizes: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
ploidy: 2

#Simulation
reps: 2500
slim path: /proj/dschridelab/lswhiteh/timesweeper/src/SLiM/build/slim
