#General
work dir: 5tp_exp
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf.slim

sample sizes: [40, 40, 40, 40, 40]
ploidy: 2

#Simulation
reps: 2500
slim path: /proj/dschridelab/lswhiteh/timesweeper/src/SLiM/build/slim
